#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YiTongBackend.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="YiTong")]
	public partial class YiTongDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbl_admin(tbl_admin instance);
    partial void Updatetbl_admin(tbl_admin instance);
    partial void Deletetbl_admin(tbl_admin instance);
    partial void Inserttbl_post(tbl_post instance);
    partial void Updatetbl_post(tbl_post instance);
    partial void Deletetbl_post(tbl_post instance);
    partial void Inserttbl_advert(tbl_advert instance);
    partial void Updatetbl_advert(tbl_advert instance);
    partial void Deletetbl_advert(tbl_advert instance);
    partial void Inserttbl_banner(tbl_banner instance);
    partial void Updatetbl_banner(tbl_banner instance);
    partial void Deletetbl_banner(tbl_banner instance);
    partial void Inserttbl_env(tbl_env instance);
    partial void Updatetbl_env(tbl_env instance);
    partial void Deletetbl_env(tbl_env instance);
    #endregion
		
		public YiTongDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["YiTongConnectionString1"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public YiTongDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public YiTongDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public YiTongDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public YiTongDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbl_admin> tbl_admins
		{
			get
			{
				return this.GetTable<tbl_admin>();
			}
		}
		
		public System.Data.Linq.Table<tbl_post> tbl_posts
		{
			get
			{
				return this.GetTable<tbl_post>();
			}
		}
		
		public System.Data.Linq.Table<tbl_advert> tbl_adverts
		{
			get
			{
				return this.GetTable<tbl_advert>();
			}
		}
		
		public System.Data.Linq.Table<tbl_banner> tbl_banners
		{
			get
			{
				return this.GetTable<tbl_banner>();
			}
		}
		
		public System.Data.Linq.Table<tbl_env> tbl_envs
		{
			get
			{
				return this.GetTable<tbl_env>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_admin")]
	public partial class tbl_admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _uid;
		
		private string _userid;
		
		private string _password;
		
		private System.DateTime _regtime;
		
		private byte _deleted;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(long value);
    partial void OnuidChanged();
    partial void OnuseridChanging(string value);
    partial void OnuseridChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnregtimeChanging(System.DateTime value);
    partial void OnregtimeChanged();
    partial void OndeletedChanging(byte value);
    partial void OndeletedChanged();
    #endregion
		
		public tbl_admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string userid
		{
			get
			{
				return this._userid;
			}
			set
			{
				if ((this._userid != value))
				{
					this.OnuseridChanging(value);
					this.SendPropertyChanging();
					this._userid = value;
					this.SendPropertyChanged("userid");
					this.OnuseridChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_regtime", DbType="DateTime NOT NULL")]
		public System.DateTime regtime
		{
			get
			{
				return this._regtime;
			}
			set
			{
				if ((this._regtime != value))
				{
					this.OnregtimeChanging(value);
					this.SendPropertyChanging();
					this._regtime = value;
					this.SendPropertyChanged("regtime");
					this.OnregtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="TinyInt NOT NULL")]
		public byte deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_post")]
	public partial class tbl_post : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _uid;
		
		private string _postcontent;
		
		private string _viewurl;
		
		private byte _isvisible;
		
		private System.DateTime _regdate;
		
		private byte _deleted;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(long value);
    partial void OnuidChanged();
    partial void OnpostcontentChanging(string value);
    partial void OnpostcontentChanged();
    partial void OnviewurlChanging(string value);
    partial void OnviewurlChanged();
    partial void OnisvisibleChanging(byte value);
    partial void OnisvisibleChanged();
    partial void OnregdateChanging(System.DateTime value);
    partial void OnregdateChanged();
    partial void OndeletedChanging(byte value);
    partial void OndeletedChanged();
    #endregion
		
		public tbl_post()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postcontent", DbType="NVarChar(1024) NOT NULL", CanBeNull=false)]
		public string postcontent
		{
			get
			{
				return this._postcontent;
			}
			set
			{
				if ((this._postcontent != value))
				{
					this.OnpostcontentChanging(value);
					this.SendPropertyChanging();
					this._postcontent = value;
					this.SendPropertyChanged("postcontent");
					this.OnpostcontentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_viewurl", DbType="NVarChar(1024) NOT NULL", CanBeNull=false)]
		public string viewurl
		{
			get
			{
				return this._viewurl;
			}
			set
			{
				if ((this._viewurl != value))
				{
					this.OnviewurlChanging(value);
					this.SendPropertyChanging();
					this._viewurl = value;
					this.SendPropertyChanged("viewurl");
					this.OnviewurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isvisible", DbType="TinyInt NOT NULL")]
		public byte isvisible
		{
			get
			{
				return this._isvisible;
			}
			set
			{
				if ((this._isvisible != value))
				{
					this.OnisvisibleChanging(value);
					this.SendPropertyChanging();
					this._isvisible = value;
					this.SendPropertyChanged("isvisible");
					this.OnisvisibleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_regdate", DbType="DateTime NOT NULL")]
		public System.DateTime regdate
		{
			get
			{
				return this._regdate;
			}
			set
			{
				if ((this._regdate != value))
				{
					this.OnregdateChanging(value);
					this.SendPropertyChanging();
					this._regdate = value;
					this.SendPropertyChanged("regdate");
					this.OnregdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="TinyInt NOT NULL")]
		public byte deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_advert")]
	public partial class tbl_advert : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _uid;
		
		private string _title;
		
		private string _imgpath;
		
		private System.DateTime _regtime;
		
		private byte _deleted;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(long value);
    partial void OnuidChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OnimgpathChanging(string value);
    partial void OnimgpathChanged();
    partial void OnregtimeChanging(System.DateTime value);
    partial void OnregtimeChanged();
    partial void OndeletedChanging(byte value);
    partial void OndeletedChanged();
    #endregion
		
		public tbl_advert()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_imgpath", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string imgpath
		{
			get
			{
				return this._imgpath;
			}
			set
			{
				if ((this._imgpath != value))
				{
					this.OnimgpathChanging(value);
					this.SendPropertyChanging();
					this._imgpath = value;
					this.SendPropertyChanged("imgpath");
					this.OnimgpathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_regtime", DbType="DateTime NOT NULL")]
		public System.DateTime regtime
		{
			get
			{
				return this._regtime;
			}
			set
			{
				if ((this._regtime != value))
				{
					this.OnregtimeChanging(value);
					this.SendPropertyChanging();
					this._regtime = value;
					this.SendPropertyChanged("regtime");
					this.OnregtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="TinyInt NOT NULL")]
		public byte deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_banner")]
	public partial class tbl_banner : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _uid;
		
		private string _title;
		
		private string _linkurl;
		
		private System.DateTime _regtime;
		
		private byte _deleted;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(long value);
    partial void OnuidChanged();
    partial void OntitleChanging(string value);
    partial void OntitleChanged();
    partial void OnlinkurlChanging(string value);
    partial void OnlinkurlChanged();
    partial void OnregtimeChanging(System.DateTime value);
    partial void OnregtimeChanged();
    partial void OndeletedChanging(byte value);
    partial void OndeletedChanged();
    #endregion
		
		public tbl_banner()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_title", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				if ((this._title != value))
				{
					this.OntitleChanging(value);
					this.SendPropertyChanging();
					this._title = value;
					this.SendPropertyChanged("title");
					this.OntitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_linkurl", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string linkurl
		{
			get
			{
				return this._linkurl;
			}
			set
			{
				if ((this._linkurl != value))
				{
					this.OnlinkurlChanging(value);
					this.SendPropertyChanging();
					this._linkurl = value;
					this.SendPropertyChanged("linkurl");
					this.OnlinkurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_regtime", DbType="DateTime NOT NULL")]
		public System.DateTime regtime
		{
			get
			{
				return this._regtime;
			}
			set
			{
				if ((this._regtime != value))
				{
					this.OnregtimeChanging(value);
					this.SendPropertyChanging();
					this._regtime = value;
					this.SendPropertyChanged("regtime");
					this.OnregtimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_deleted", DbType="TinyInt NOT NULL")]
		public byte deleted
		{
			get
			{
				return this._deleted;
			}
			set
			{
				if ((this._deleted != value))
				{
					this.OndeletedChanging(value);
					this.SendPropertyChanging();
					this._deleted = value;
					this.SendPropertyChanged("deleted");
					this.OndeletedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbl_env")]
	public partial class tbl_env : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _uid;
		
		private string _item;
		
		private string _value;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuidChanging(long value);
    partial void OnuidChanged();
    partial void OnitemChanging(string value);
    partial void OnitemChanged();
    partial void OnvalueChanging(string value);
    partial void OnvalueChanged();
    #endregion
		
		public tbl_env()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uid", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long uid
		{
			get
			{
				return this._uid;
			}
			set
			{
				if ((this._uid != value))
				{
					this.OnuidChanging(value);
					this.SendPropertyChanging();
					this._uid = value;
					this.SendPropertyChanged("uid");
					this.OnuidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_item", DbType="NVarChar(1000)")]
		public string item
		{
			get
			{
				return this._item;
			}
			set
			{
				if ((this._item != value))
				{
					this.OnitemChanging(value);
					this.SendPropertyChanging();
					this._item = value;
					this.SendPropertyChanged("item");
					this.OnitemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_value", DbType="NVarChar(1000)")]
		public string value
		{
			get
			{
				return this._value;
			}
			set
			{
				if ((this._value != value))
				{
					this.OnvalueChanging(value);
					this.SendPropertyChanging();
					this._value = value;
					this.SendPropertyChanged("value");
					this.OnvalueChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
